#tomcat
server:
  port: 2003

spring:
  application:
    name: alibaba-seata-account
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1



seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seata_tx_group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  service:
    grouplist:
      default: localhost:8091
    vgroup-mapping:
      seata_tx_group: default
  config:
    type: nacos
    nacos:
      namespace: ""
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: ""
      username: nacos
      password: nacos

logging:
  level:
    com.alibaba.nacos.client.*: WARN